### ISSUE TITLE
@secured annotation does not work with actions

### ISSUE THREAD

**Issue by janmarek** [nextras/secured-links#1]
It seems that only signals can be protected. But I usually use render or action methods for actions which should be protected (e.g. renderDelete).

**Comment by hrach** [comment]
Currently, Nette has a custom solution for [CSRF protection](https://doc.nette.org/en/vulnerability-protection#toc-cross-site-request-forgery-csrf). We do not plan any further feature development in this library, therefore I'm closing this ticket.
