### ISSUE TITLE
Support parameters with object values

### ISSUE THREAD

**Issue by JanTvrdik** [nextras/secured-links#14]
We currently use in are app ugly workaround

~~~php
$params = array_map(
	function ($param) {
		return is_object($param) && method_exists($param, 'getId') ? $param->getId() : $param;
	},
	$params
);
~~~

**Comment by hrach** [comment]
Currently, Nette has a custom solution for [CSRF protection](https://doc.nette.org/en/vulnerability-protection#toc-cross-site-request-forgery-csrf). We do not plan any further feature development in this library, therefore I'm closing this ticket.
