### ISSUE TITLE
Exception in random_bytes

### ISSUE THREAD

**Issue by peterpp** [nextras/secured-links#17]
Function random_bytes from paragonie/random_compat library can throw an exception. It is very rare situation, but it really happens on our production server. I suggest to encapsulate this code:

```
$session->token = function_exists('random_bytes')
    ? random_bytes(16)
    : Nette\Utils\Random::generate(16, "\x00-\xFF");
```

to try/catch block. In catch will be Random::generate()

**Comment by hrach** [comment]
Since also the core function may throw an exception, this should be implemented regardless the polyfill behavior.

**Comment by JanTvrdik** [comment]
@peterpp I disagree, the behavior is correct. Adding fallback would just decrease security.

**Comment by hrach** [comment]
The "fallback" may be a repeated call. That does not decrease security.
Second, this potential "security" issue seems as useless garbage to me - similarly as the reason why this is not in the Nette framework itself - not strong enough to decrease the usability.

**Comment by JanTvrdik** [comment]
AFAIK, the only situation when PHP native `random_bytes` can fail in real-world is when the underlying operating system is deeply fucked.

If this is a problem of the polyfill, I'm open to changing the code the 

~~~php
$session->token = PHP_VERSION_ID >= 70000 && function_exists('random_bytes')
    ? random_bytes(16)
    : Nette\Utils\Random::generate(16, "\x00-\xFF");
~~~

**Comment by peterpp** [comment]
@JanTvrdik Looks fine to me 👍. The problem on our server is that /dev/urandom is not accesible for some projects 😇

**Comment by peterpp** [comment]
Any chance to implement this `PHP_VERSION_ID >= 70000` condition? Or we can wait until PHP 5.6 will be dead for good 🙂

**Comment by hrach** [comment]
Well, PHP 5.6 is dead for good. :) https://www.php.net/supported-versions.php
Closing
