### ISSUE TITLE
Incompatibility with nette/application 3.1.5

### ISSUE THREAD

**Issue by natocTo** [nextras/secured-links#33]
Tento PR https://github.com/nextras/secured-links/pull/31 co se dělal pro verzi 3.1.4 nefunguje na verzi 3.1.5 https://github.com/nette/application/releases/tag/v3.1.5. 
Vypadá že tam někdo reportoval že to byl asi BC break tak se to vrátilo do stavu jak to bylo před verzí 3.1.4.

Nevím zda by stačil revert toho PR pouze nebo už není žádoucí vracet PHP 7.1.

**Comment by hrach** [comment]
Uz bych PHP 7.1 nevracel. Poslani PR pomuze :)

**Comment by Ivorius** [comment]
Šlo by to vydat?

**Comment by hrach** [comment]
Published as 1.9.0
