### ISSUE TITLE
Compatibility with PHP < 8.0

### ISSUE THREAD

**Issue by peterpp** [nextras/secured-links#38]
This library declares compatibility with PHP `^7.2` in composer.json. However, release 1.10.0 requires PHP 8.0. because it uses `ReflectionClass::getAttributes()` method.

**Comment by hrach** [comment]
Oh sorry, that's a bug. @haltuf would you please fix it?

**Comment by hrach** [comment]
Fixed by #39

**Comment by hrach** [comment]
Released as v1.10.1
