### ISSUE TITLE
PHP 8 requires both annotation and attribute to create secured link

### ISSUE THREAD

**Issue by forgie1** [nextras/secured-links#40]
see this commit: https://github.com/nextras/secured-links/commit/752ad93fbf2e6fc1d4d9f29dcec823c25372335b

**Comment by forgie1** [comment]
@hrach  should be fixed by https://github.com/nextras/secured-links/pull/41

**Comment by hrach** [comment]
Thank you for reporting this. Closed in #42 and released as 1.10.2.
