### ISSUE TITLE
Nette/Utils

### ISSUE THREAD

**Issue by ViPErCZ** [nextras/secured-links#43]
Kde to pouziva Nette/Utils? Koukal jsem do src, ale bud jsem slepej a nebo jsem to v hlavicce nikde nenasel?
Pokud nejsem slepej, tak vyhodit z composer.json?

**Comment by mabar** [comment]
https://github.com/nextras/secured-links/blob/057b3d903c983bbd2e292663d717e956dd83b50a/src/Helpers.php#L36

**Comment by ViPErCZ** [comment]
Tak ze jsem slepej.... omg a to je teprve streda. :-/
Diky.

**Comment by JanTvrdik** [comment]
well that could be replaces with `random_bytes`

**Comment by ViPErCZ** [comment]
Proč jsem se k tomu vlastně dostal... protože samozřejmě nešlo povýšit Utils na verzi 4. ;-)
