### ISSUE TITLE
New release with `nette/utils` version `4`

### ISSUE THREAD

**Issue by harmim** [nextras/secured-links#45]
Can you please create a new release of the package? In particular, I need `nette/utils` version `4` to be in the new release, i.e., the following commit https://github.com/nextras/secured-links/commit/c5a01379ccea5c28ca3216570a1ec72dd313e18e. Thanks a lot.

**Comment by xificurk** [comment]
@hrach :pray:

**Comment by matoni555** [comment]
@hrach 🙏

**Comment by hrach** [comment]
Sorry for the delay.
https://github.com/nextras/secured-links/releases/tag/v1.10.3
